language: node_js
node_js:
- node
before_install:
- npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
deploy:
  provider: npm
  email: keith30895@gmail.com
  api_key:
    secure: jIEs5XQftQbtf7GXXa2sPHK3j5ClomY56c0Z7qv6PlA8nwENj8obd6eHH7XhY85K0Gb+tI1xNTliaQT2jLmSdfUOVojh9ZJ/dutH+mMVVUQMa4n7hQuWHbuQraLL5WtyN/PQCrHJpi2Ylu7katuJqqQhZrnpnVtgO+A8NJu7E561DZ1blBvOjT+/3pcSGnKaxK+c6qekRwMDQpTQjkrEg9LZc+cxqZzu37qr0rZ7HgGyuGRIeWxm7PDxFXA25KQ+o4244KTk0+jDac+TRTN7lKyFozkQLK+nM7G0yhITvJzKxmWLSborZ1Gx3r4YO6pPNF37Mly4WUzCk3nAT6653M4Tv5bjmyBHHnb/B/TLGmNr2na6I1z81+AuQGdaUtV1dIW400ZCUI82yAl2jrv691zzXcjQ1b30CKe+PteIPvxEQ+wkA/wBdX4ejh6YwGIFbxcQdoimuMrFzTW36boU0myKpMVyVOXZIndi8SVcK7p7d1UIhJUdUak4UJiMOuCCZc8l/gKYy0zgUAsqasba1H1sDED4izErTFMlaeospfobHPdqybp8Ilc+qNW7V0RHlC6mkvtAmn4pBx4PJRMXs22ZSTMzF6zGv4HPKy/0/VrmcqSBT+DXX042nOpThnthUOBLhTkBZOfznZ56j4FEsu51DGnvuANz4u1m60ZXHQQ=
  on:
    repo: Keith3895/pubSub
branches:
  only:
  - master
